name: zkemail-cairo-ci

on:
  push:
    branches:
      - "**"

jobs:
  check:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Cairo0
        run: make

      - name: Run Rust fmt check
        run: cargo fmt --all -- --check

      - name: Run Rust clippy check
        run: cargo clippy -- -D warnings
      
      - name: Run Cairo fmt check
        run: make format-check

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Cairo0
        run: make

      - name: Install Nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run

